class Product {
  final String id;
  String name;
  String category;
  double price;
  String imageEmoji;
  String description;
  bool isAvailable;
  int stock;
  int minStock;

  Product({
    required this.id,
    required this.name,
    required this.category,
    required this.price,
    required this.imageEmoji,
    this.description = '',
    this.isAvailable = true,
    this.stock = 50,
    this.minStock = 10,
  });

  Product copyWith({
    String? name,
    String? category,
    double? price,
    String? imageEmoji,
    String? description,
    bool? isAvailable,
    int? stock,
    int? minStock,
  }) {
    return Product(
      id: id,
      name: name ?? this.name,
      category: category ?? this.category,
      price: price ?? this.price,
      imageEmoji: imageEmoji ?? this.imageEmoji,
      description: description ?? this.description,
      isAvailable: isAvailable ?? this.isAvailable,
      stock: stock ?? this.stock,
      minStock: minStock ?? this.minStock,
    );
  }
}

List<Product> buildDummyProducts() => [
  // KHS
  Product(
    id: 'khs01',
    name: 'KHS kelapa',
    category: 'KHS',
    price: 8000,
    imageEmoji: '🍵',
    description: 'Kelapa muda premium pilihan',
    stock: 45,
    minStock: 10,
  ),
  Product(
    id: 'khs02',
    name: 'KHS Keju',
    category: 'KHS',
    price: 10000,
    imageEmoji: '🧀',
    description: 'Keju premium pilihan',
    stock: 8,
    minStock: 10,
  ),
  // Coklat
  Product(
    id: 'ckt01',
    name: 'KHS Coklat',
    category: 'Coklat',
    price: 12000,
    imageEmoji: '🍫',
    description: 'coklat pilihan',
    stock: 30,
    minStock: 8,
  ),
  Product(
    id: 'ckt02',
    name: 'KHS Coklat Kacang',
    category: 'Coklat',
    price: 12000,
    imageEmoji: '🥜',
    description: 'ketan kacang premium pilihan',
    stock: 3,
    minStock: 5,
  ),
  Product(
    id: 'ckt03',
    name: 'KHS Coklat Keju',
    category: 'Coklat',
    price: 14000,
    imageEmoji: '🧀',
    description: 'coklat keju premium pilihan',
    stock: 60,
    minStock: 15,
  ),
  Product(
    id: 'ckt04',
    name: 'KHS Coklat regal',
    category: 'Coklat',
    price: 14000,
    imageEmoji: '🍪',
    description: 'coklat regal premium pilihan',
    stock: 55,
    minStock: 10,
  ),
  Product(
    id: 'ckt05',
    name: 'KHS Coklat Crunchy',
    category: 'Coklat',
    price: 14000,
    imageEmoji: '🧇',
    description: 'coklat crunchy premium pilihan',
    stock: 12,
    minStock: 10,
  ),
  Product(
    id: 'ckt06',
    name: 'KHS Coklat crunchy keju',
    category: 'Coklat',
    price: 16000,
    imageEmoji: '🧀',
    description: 'coklat crunchy keju premium pilihan',
    stock: 40,
    minStock: 10,
  ),
  // Green Tea
  Product(
    id: 'gt01',
    name: 'KHS Green Tea',
    category: 'Green Tea',
    price: 12000,
    imageEmoji: '🍵',
    description: 'Green tea pilihan',
    stock: 15,
    minStock: 8,
  ),
  Product(
    id: 'gt02',
    name: 'KHS Green Tea Keju',
    category: 'Green Tea',
    price: 14000,
    imageEmoji: '🧀',
    description: 'green tea premium pilihan',
    stock: 0,
    minStock: 5,
  ),
  Product(
    id: 'gt03',
    name: 'Green Tea Almond',
    category: 'Green Tea',
    price: 12000,
    imageEmoji: '🌰',
    description: 'green tea almond premium pilihan',
    stock: 20,
    minStock: 5,
  ),
  Product(
    id: 'gt04',
    name: 'KHS Green Tea Crunchy',
    category: 'Green Tea',
    price: 14000,
    imageEmoji: '🧇',
    description: 'green tea crunchy premium pilihan',
    stock: 7,
    minStock: 8,
  ),
  Product(
    id: 'gt05',
    name: 'KHS Green Tea Crunchy Keju',
    category: 'Green Tea',
    price: 14000,
    imageEmoji: '🧀',
    description: 'green tea crunchy keju premium pilihan',
    stock: 25,
    minStock: 8,
  ),
  // Milo
  Product(
    id: 'ml01',
    name: 'KHS Milo',
    category: 'Milo',
    price: 12000,
    imageEmoji: '🥤',
    description: 'milo pilihan',
    stock: 18,
    minStock: 8,
  ),
  Product(
    id: 'ml02',
    name: 'KHS Milo Coco Krunch',
    category: 'Milo',
    price: 14000,
    imageEmoji: '🥣',
    description: 'milo coco krunch premium pilihan',
    stock: 22,
    minStock: 8,
  ),
  Product(
    id: 'ml03',
    name: 'KHS Milo Keju',
    category: 'Milo',
    price: 14000,
    imageEmoji: '🧀',
    description: 'milo keju premium pilihan',
    stock: 10,
    minStock: 5,
  ),
  // Taro
  Product(
    id: 'tr01',
    name: 'KHS Taro',
    category: 'Taro',
    price: 12000,
    imageEmoji: '🍠',
    description: 'taro premium pilihan',
    stock: 10,
    minStock: 5,
  ),
  Product(
    id: 'tr02',
    name: 'KHS Taro Keju',
    category: 'Taro',
    price: 14000,
    imageEmoji: '🧀',
    description: 'taro keju premium pilihan',
    stock: 10,
    minStock: 5,
  ),
  // Alpukat
  Product(
    id: 'apt01',
    name: 'KHS Alpukat',
    category: 'Alpukat',
    price: 21000,
    imageEmoji: '🥑',
    description: 'alpukat asli premium pilihan',
    stock: 10,
    minStock: 5,
  ),
  Product(
    id: 'apt02',
    name: 'KHS Alpukat Coklat',
    category: 'Alpukat',
    price: 14000,
    imageEmoji: '🥑',
    description: 'alpukat coklat premium pilihan',
    stock: 10,
    minStock: 5,
  ),
  Product(
    id: 'apt03',
    name: 'KHS Alpukat Coklat Keju',
    category: 'Alpukat',
    price: 16000,
    imageEmoji: '🧀',
    description: 'alpukat coklat premium pilihan',
    stock: 10,
    minStock: 5,
  ),
  // Strawberry
  Product(
    id: 'stb01',
    name: 'KHS Strawberry',
    category: 'Strawberry',
    price: 15000,
    imageEmoji: '🍓',
    description: 'strawberry premium pilihan',
    stock: 10,
    minStock: 5,
  ),
  Product(
    id: 'stb02',
    name: 'KHS Strawberry Keju',
    category: 'Strawberry',
    price: 17000,
    imageEmoji: '🧀',
    description: 'strawberry premium pilihan',
    stock: 10,
    minStock: 5,
  ),
  Product(
    id: 'stb03',
    name: 'KHS Strawberry Coklat',
    category: 'Strawberry',
    price: 14000,
    imageEmoji: '🍫',
    description: 'strawberry coklat premium pilihan',
    stock: 10,
    minStock: 5,
  ),
  Product(
    id: 'stb04',
    name: 'KHS Strawberry Ice Cream',
    category: 'Strawberry',
    price: 21000,
    imageEmoji: '🍨',
    description: 'strawberry premium pilihan',
    stock: 10,
    minStock: 5,
  ),
  // Durian
  Product(
    id: 'dr01',
    name: 'KHS Durian',
    category: 'Durian',
    price: 15000,
    imageEmoji: '🍈',
    description: 'durian premium pilihan',
    stock: 10,
    minStock: 5,
  ),
  Product(
    id: 'dr02',
    name: 'KHS Durian Keju',
    category: 'Durian',
    price: 18000,
    imageEmoji: '🧀',
    description: 'durian premium pilihan',
    stock: 10,
    minStock: 5,
  ),
  // Mangga
  Product(
    id: 'mg01',
    name: 'KHS Mangga',
    category: 'Mangga',
    price: 14000,
    imageEmoji: '🥭',
    description: 'mangga premium pilihan',
    stock: 10,
    minStock: 5,
  ),
  Product(
    id: 'mg02',
    name: 'KHS Mangga Keju',
    category: 'Mangga',
    price: 16000,
    imageEmoji: '🧀',
    description: 'mangga premium pilihan',
    stock: 10,
    minStock: 5,
  ),
  Product(
    id: 'mg03',
    name: 'KHS Mangga Ice Cream',
    category: 'Mangga',
    price: 20000,
    imageEmoji: '🍨',
    description: 'mangga premium pilihan',
    stock: 10,
    minStock: 5,
  ),
  // Tiramisu
  Product(
    id: 'trm01',
    name: 'KHS Tiramisu',
    category: 'Tiramisu',
    price: 12000,
    imageEmoji: '🍰',
    description: 'tiramisu premium pilihan',
    stock: 10,
    minStock: 5,
  ),
  Product(
    id: 'trm02',
    name: 'KHS Tiramisu Keju',
    category: 'Tiramisu',
    price: 14000,
    imageEmoji: '🧀',
    description: 'tiramisu premium pilihan',
    stock: 10,
    minStock: 5,
  ),
  Product(
    id: 'trm03',
    name: 'KHS Tiramisu Regal',
    category: 'Tiramisu',
    price: 14000,
    imageEmoji: '🍪',
    description: 'tiramisu coklat premium pilihan',
    stock: 10,
    minStock: 5,
  ),
  // Vanila X Red Velvet
  Product(
    id: 'vxr01',
    name: 'KHS Vanila',
    category: 'Vanila X Red Velvet',
    price: 12000,
    imageEmoji: '🍦',
    description: 'vanila premium pilihan',
    stock: 10,
    minStock: 5,
  ),
  Product(
    id: 'vxr02',
    name: 'KHS Vanila Keju',
    category: 'Vanila X Red Velvet',
    price: 14000,
    imageEmoji: '🧀',
    description: 'vanila keju premium pilihan',
    stock: 10,
    minStock: 5,
  ),
  Product(
    id: 'vxr03',
    name: 'KHS Vanila Red Velvet',
    category: 'Vanila X Red Velvet',
    price: 16000,
    imageEmoji: '🍰',
    description: 'vanila red velvet premium pilihan',
    stock: 10,
    minStock: 5,
  ),
  // Traditional Series
  Product(
    id: 'trd01',
    name: 'KHS Oncom',
    category: 'Traditional Series',
    price: 8000,
    imageEmoji: '🍘',
    description: 'oncom premium pilihan',
    stock: 10,
    minStock: 5,
  ),
  Product(
    id: 'trd02',
    name: 'KHS Abon Ayam',
    category: 'Traditional Series',
    price: 12000,
    imageEmoji: '🍗',
    description: 'abon ayam premium pilihan',
    stock: 10,
    minStock: 5,
  ),
  Product(
    id: 'trd03',
    name: 'KHS Abon Sapi',
    category: 'Traditional Series',
    price: 14000,
    imageEmoji: '🥩',
    description: 'Abon Sapi premium pilihan',
    stock: 10,
    minStock: 5,
  ),
  Product(
    id: 'trd04',
    name: 'KHS Abon Tongkol',
    category: 'Traditional Series',
    price: 14000,
    imageEmoji: '🐟',
    description: 'Abon Tongkol premium pilihan',
    stock: 10,
    minStock: 5,
  ),
  //drinks
  Product(
    id: 'drk01',
    name: 'Klepon Original',
    category: 'Drinks',
    price: 10000,
    imageEmoji: '🟢',
    description: 'klepon pilihan',
    stock: 10,
    minStock: 5,
  ),
  Product(
    id: 'drk02',
    name: 'Klepon Whypy Cream',
    category: 'Drinks',
    price: 13000,
    imageEmoji: '🍦',
    description: 'Cream pilihan',
    stock: 10,
    minStock: 5,
  ),
  Product(
    id: 'drk03',
    name: 'Klepon With Topping ',
    category: 'Drinks',
    price: 13000,
    imageEmoji: '🍡',
    description: '',
    stock: 10,
    minStock: 5,
  ),
  Product(
    id: 'mjs01',
    name: 'Mojito Manggo',
    category: 'Mojito Series',
    price: 8000,
    imageEmoji: '🥭',
    description: 'mangga segar',
    stock: 10,
    minStock: 5,
  ),
  Product(
    id: 'mjs02',
    name: 'Mojito Green Apple',
    category: 'Mojito Series',
    price: 8000,
    imageEmoji: '🍏',
    description: 'Abon Tongkol premium pilihan',
    stock: 10,
    minStock: 5,
  ),
  Product(
    id: 'mjs03',
    name: 'Mojito Blueberry',
    category: 'Mojito Series',
    price: 8000,
    imageEmoji: '🫐',
    description: '',
    stock: 10,
    minStock: 5,
  ),
  Product(
    id: 'mjs04',
    name: 'Mojito Strawberry',
    category: 'Mojito Series',
    price: 8000,
    imageEmoji: '🍓',
    description: '',
    stock: 10,
    minStock: 5,
  ),
  Product(
    id: 'scr01',
    name: 'Manggo',
    category: 'Sticky Rice',
    price: 15000,
    imageEmoji: '🥭',
    description: '',
    stock: 10,
    minStock: 5,
  ),
  Product(
    id: 'ts01',
    name: 'Spicced Apple Tea',
    category: 'Tea Series',
    price: 8000,
    imageEmoji: '🍎',
    description: '',
    stock: 10,
    minStock: 5,
  ),
  Product(
    id: 'ts02',
    name: 'Lasmine Tea',
    category: 'Tea Series',
    price: 8000,
    imageEmoji: '🌸',
    description: '',
    stock: 10,
    minStock: 5,
  ),
  Product(
    id: 'cp01',
    name: 'Jeli Rainbows',
    category: 'Campur',
    price: 4000,
    imageEmoji: '🌈',
    description: '',
    stock: 10,
    minStock: 5,
  ),
  Product(
    id: 'cp02',
    name: 'Pudding',
    category: 'Campur',
    price: 4000,
    imageEmoji: '🍮',
    description: '',
    stock: 10,
    minStock: 5,
  ),
  Product(
    id: 'cp03',
    name: 'Black Boba',
    category: 'Campur',
    price: 4000,
    imageEmoji: '🧋',
    description: '',
    stock: 10,
    minStock: 5,
  ),
  Product(
    id: 'cp04',
    name: 'Chestnut Boba',
    category: 'Campur',
    price: 4000,
    imageEmoji: '🌰',
    description: '',
    stock: 10,
    minStock: 5,
  ),
  Product(
    id: 'cp05',
    name: 'Jeli Pearl',
    category: 'Campur',
    price: 4000,
    imageEmoji: '⚪',
    description: '',
    stock: 10,
    minStock: 5,
  ),
  Product(
    id: 'cp06',
    name: 'Pudding Boba',
    category: 'Campur',
    price: 4000,
    imageEmoji: '🍮',
    description: '',
    stock: 10,
    minStock: 5,
  ),
  Product(
    id: 'cp07',
    name: 'Ice Cream',
    category: 'Campur',
    price: 4000,
    imageEmoji: '🍨',
    description: '',
    stock: 10,
    minStock: 5,
  ),
];

final List<String> productCategories = [
  'ALL',
  'KHS',
  'Coklat',
  'Green Tea',
  'Milo',
  'Taro',
  'Alpukat',
  'Strawberry',
  'Durian',
  'Mangga',
  'Tiramisu',
  'Vanila X Red Velvet',
  'Traditional Series',
  'Drinks',
  'Mojito Series',
  'Sticky Rice',
  'Tea Series',
  'Campur'
];
